# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lzpz3BOi5IEdUDZ58_G2r8ouKyMyzz4e
"""

import pandas as pd
import numpy as np
data=pd.read_csv('/content/Iris.csv')
data

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Species']=le.fit_transform(data['Species'])
data

x=data.drop(columns=['Species'],axis=1)
y=data['Species']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print('accuracy is:',accuracy)











